name = "Zenoh"
uuid = "b742139f-8771-480b-a9b2-33222b45d29b"
authors = ["Benjamin Chung <ckfinite@gmail.com>"]
version = "0.1.4"

[deps]
CClosure = "6238cdf7-1651-426a-bbec-388a63a3d275"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
libzenohc_jll = "938f45e1-bfa9-5428-95ae-33d45742c18e"

[compat]
CClosure = "0.1.0"
CEnum = "0.5.0"
Dates = "1.11.0"
Libdl = "1.11.0"
libzenohc_jll = "^1.6.2"
julia = "1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zenohd_jll = "60fe4315-4d9d-51d2-90b3-f4c2062225d6"

[targets]
test = ["Test", "Zenohd_jll", "BenchmarkTools"]
