[general]
library_name = "libzenohc"
output_file_path = "./LibZenohC.jl"
module_name = "LibZenohC"
jll_pkg_name = "libzenohc_jll"
export_symbol_prefixes = ["z_", "zc_", "ze_"]
output_ignorelist =["Z_RELIABILITY_DEFAULT"]
prologue_file_path="prologue.jl"

[codegen]
field_access_method_list = [
    "z_publisher_options_t",
    "z_query_consolidation_t",
    "z_delete_options_t",
    "z_get_options_t",
    "z_liveliness_subscriber_options_t",
    "z_liveliness_get_options_t",
    "z_publisher_delete_options_t",
    "z_publisher_put_options_t",
    "z_put_options_t",
    "z_query_reply_options_t",
    "z_query_reply_del_options_t",
    "z_query_reply_err_options_t",
    "z_scout_options_t"
]